name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        run:  cargo fmt --check
      - name: Clippy
        run: cargo clippy --tests --all-targets --locked -- -Dwarnings